// 1. Layouts let you wrap all child pages inside some logic

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       {/* if i add something here , it will be on all the pages , basically layout.tsx provides
           the layout for all pages , what you will add here will be shown across all the pages ,
           if you want some layout over some specific routes , lets say youu want some text to be shown
           only on signin page , then you have create a layout.tsx file in signin folder 
        */}
        <div>This is my navBar</div>
        {children}
      </body>
    </html>
  );
}
